[project]
name = "dataScience"
version = "0.1.0"
description = "Korepetycje z data science"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipyk>=0.1.4.2",
    "kagglehub>=0.3.11",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]
